
export enum NodeType {
  INTRO = 'INTRO',
  SCENARIO = 'SCENARIO',
  HUB = 'HUB',
  QUIZ = 'QUIZ'
}

export enum InteractionType {
  NONE = 'NONE',
  BALLOONS = 'BALLOONS', // Pop incorrect statements
  DRAG_SHIELD = 'DRAG_SHIELD', // Drag shield to protected scenarios
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
  CODE_CRACKER = 'CODE_CRACKER', // Final 4-digit code
  CITY_HALL_SUB_LOCATIONS = 'CITY_HALL_SUB_LOCATIONS' // Visit 4 sub-locations before decision
}

export type Language = 'he' | 'en' | 'ar';

export interface ChatMessage {
  id: string;
  speaker: string;
  text: string;
  isPlayer?: boolean;
  mood?: 'neutral' | 'angry' | 'happy' | 'concerned';
}

export interface DecisionOption {
  id: string;
  text: string;
  feedback: string; // The immediate response after choosing
  scoreImpact?: number;
}

export interface DigitalContent {
  type: 'POST' | 'ARTICLE' | 'IMAGE';
  title?: string;
  content: string;
  likes?: number;
  author?: string;
  imageUrl?: string; // Generated by Gemini
}

export interface QuizQuestion {
  id: string;
  question: string;
  options: { text: string; value: number }[]; // Value is the digit for the code
  correctValue: number;
  explanation: string;
}

export interface SubScene {
  id: string;
  title: string;
  icon: string; // Emoji or icon name
  dialog: ChatMessage[];
  backgroundImage?: string; // Specific background for this sub-location
}

export interface SceneData {
  description: string;
  backgroundImage?: string; // Generated by Gemini
  characterImages?: Record<string, string>; // Map speaker name to Image URL
  digitalContent?: DigitalContent;
  dialog: ChatMessage[];
  interactionType: InteractionType;
  interactionData?: any; // Flexible data for mini-games
  subScenes?: SubScene[]; // For City Hall style nested interactions
  decisionQuestion: string;
  options: DecisionOption[];
  moreInfoTitle?: string;
  moreInfoContent?: string; // For the Bottom Sheet
}

export interface GameNode {
  id: string;
  title: string;
  type: NodeType;
  isLocked: boolean;
  isCompleted: boolean;
  coordinates?: { x: number; y: number }; // Percentage position on map (0-100)
  data: SceneData;
}

export interface GameState {
  currentNodeId: string | null; // null means Intro screen
  nodes: GameNode[];
  score: number;
  devMode: boolean;
}